-- liquibase formatted sql

-- changeset reedws:2025-06-26-1 labels:v1.0.0
CREATE SCHEMA identity;

-- changeset reedws:2025-06-26-2 labels:v1.0.0
CREATE TABLE "identity"."permissions" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "action_id" INTEGER NOT NULL, "subject_id" INTEGER NOT NULL, "inverted" BOOLEAN DEFAULT FALSE NOT NULL, CONSTRAINT "permissions_pkey" PRIMARY KEY ("id"));

-- changeset reedws:2025-06-26-3 labels:v1.0.0
CREATE TABLE "identity"."related_permissions" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "permission_id" INTEGER NOT NULL, "related_permission_id" INTEGER NOT NULL, CONSTRAINT "related_permissions_pkey" PRIMARY KEY ("id"));

-- changeset reedws:2025-06-26-4 labels:v1.0.0
CREATE TABLE "identity"."subjects" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "active" BOOLEAN DEFAULT TRUE NOT NULL, CONSTRAINT "subjects_pkey" PRIMARY KEY ("id"));

-- changeset reedws:2025-06-26-5 labels:v1.0.0
CREATE TABLE "identity"."actions" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, CONSTRAINT "actions_pkey" PRIMARY KEY ("id"));

-- changeset reedws:2025-06-26-6 labels:v1.0.0
CREATE TABLE "identity"."role_permissions" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "role_id" INTEGER NOT NULL, "permission_id" INTEGER NOT NULL, CONSTRAINT "role_permissions_pkey" PRIMARY KEY ("id"));

-- changeset reedws:2025-06-26-7 labels:v1.0.0
CREATE TABLE "identity"."roles" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(255) NOT NULL, "code" VARCHAR(255) NOT NULL, "deleted_by" INTEGER, "created_by" INTEGER NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" INTEGER NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "roles_pkey" PRIMARY KEY ("id"));

-- changeset reedws:2025-06-26-8 labels:v1.0.0
CREATE TABLE "identity"."users" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "first_name" VARCHAR(255) NOT NULL, "last_name" VARCHAR(255) NOT NULL,  "login_attempts" INTEGER, "locked_at" TIMESTAMP WITH TIME ZONE, "email" VARCHAR(255) NOT NULL, "password" VARCHAR(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "created_by" INTEGER NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "updated_by" INTEGER, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" INTEGER, CONSTRAINT "users_pkey" PRIMARY KEY ("id"));

-- changeset reedws:2025-06-26-9 labels:v1.0.0
CREATE TABLE "identity"."user_roles" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "user_id" INTEGER NOT NULL, "role_id" INTEGER NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE, "created_by" INTEGER, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" INTEGER, "updated_at" TIMESTAMP WITH TIME ZONE, "updated_by" INTEGER, CONSTRAINT "user_roles_pkey" PRIMARY KEY ("id"));

-- changeset reedws:2025-06-26-10 labels:v1.0.0
ALTER TABLE "identity"."subjects" ADD CONSTRAINT "subjects_code_key" UNIQUE ("code");

-- changeset reedws:2025-06-26-11 labels:v1.0.0
ALTER TABLE "identity"."actions" ADD CONSTRAINT "actions_code_key" UNIQUE ("code");

-- changeset reedws:2025-06-26-12 labels:v1.0.0
ALTER TABLE "identity"."users" ADD CONSTRAINT "users_email_key" UNIQUE ("email");

-- changeset reedws:2025-06-26-13 labels:v1.0.0
ALTER TABLE "identity"."user_roles" ADD CONSTRAINT "user_roles_user_id_key" UNIQUE ("user_id");

-- changeset reedws:2025-06-26-14 labels:v1.0.0
ALTER TABLE "identity"."permissions" ADD CONSTRAINT "permissions_action_id_fkey" FOREIGN KEY ("action_id") REFERENCES "identity"."actions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-06-26-15 labels:v1.0.0
ALTER TABLE "identity"."permissions" ADD CONSTRAINT "permissions_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "identity"."subjects" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-06-26-16 labels:v1.0.0
ALTER TABLE "identity"."related_permissions" ADD CONSTRAINT "related_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "identity"."permissions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-06-26-17 labels:v1.0.0
ALTER TABLE "identity"."related_permissions" ADD CONSTRAINT "related_permissions_related_permission_id_fkey" FOREIGN KEY ("related_permission_id") REFERENCES "identity"."permissions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-06-26-18 labels:v1.0.0
ALTER TABLE "identity"."role_permissions" ADD CONSTRAINT "role_permissions_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "identity"."permissions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-06-26-19 labels:v1.0.0
ALTER TABLE "identity"."role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "identity"."roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-06-26-20 labels:v1.0.0
ALTER TABLE "identity"."roles" ADD CONSTRAINT "roles_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-06-26-21 labels:v1.0.0
ALTER TABLE "identity"."roles" ADD CONSTRAINT "roles_deleted_by_fkey" FOREIGN KEY ("deleted_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-06-26-22 labels:v1.0.0
ALTER TABLE "identity"."roles" ADD CONSTRAINT "roles_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-06-26-23 labels:v1.0.0
ALTER TABLE "identity"."user_roles" ADD CONSTRAINT "user_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "identity"."roles" ("id") ON UPDATE CASCADE ON DELETE CASCADE;

-- changeset reedws:2025-06-26-33 labels:v1.0.0
ALTER TABLE "identity"."user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "identity"."users" ("id") ON UPDATE CASCADE ON DELETE CASCADE;

-- changeset reedws:2025-06-26-43 labels:v1.0.0
ALTER TABLE "identity"."users" ADD CONSTRAINT "users_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-06-26-44 labels:v1.0.0
ALTER TABLE "identity"."users" ADD CONSTRAINT "users_deleted_by_fkey" FOREIGN KEY ("deleted_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-06-26-45 labels:v1.0.0
ALTER TABLE "identity"."users" ADD CONSTRAINT "users_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-06-26-46 labels:v1.0.0
INSERT INTO identity.users (first_name, last_name, email, password, created_by, created_at, updated_by, updated_at, deleted_by, deleted_at) VALUES ('IT', 'Solutions Center', 'itsolctr@ucmail.uc.edu', '$2b$10$R8KXMnq14SyqrmAv7om0JOwr68Y0ZJgJyVp7LZNncbMbkfNPrwM/u', 1, NOW(), 1, NOW(), NULL, NULL);

-- changeset reedws:2025-06-26-47 labels:v1.0.0
INSERT INTO "identity".subjects(code, name, active) VALUES
	('USER', 'Users', TRUE),
	('ROLE', 'Roles', TRUE);

INSERT INTO "identity".actions(code, name) VALUES
	('UPDATE', 'Edit / Update'),
	('READ', 'Read'),
	('DELETE', 'Delete'),
	('RESTORE', 'Restore'),
	('CREATE', 'Create');

INSERT INTO "identity".roles(name, code, created_by, created_at, updated_by, updated_at) VALUES
	('Admin', 'ADMIN', (SELECT id FROM identity.users WHERE email = 'itsolctr@ucmail.uc.edu'), NOW(), (SELECT id FROM identity.users WHERE email = 'itsolctr@ucmail.uc.edu'), NOW());

INSERT INTO "identity".user_roles(user_id, role_id, created_by, created_at, updated_by, updated_at) VALUES
	(
    (SELECT id FROM identity.users WHERE email = 'itsolctr@ucmail.uc.edu'),
    (SELECT id FROM identity.roles WHERE code = 'ADMIN'),
    (SELECT id FROM identity.users WHERE email = 'itsolctr@ucmail.uc.edu'),
    NOW(),
    (SELECT id FROM identity.users WHERE email = 'itsolctr@ucmail.uc.edu'),
    NOW()
  );

-- changeset reedws:2025-06-26-48 labels:v1.0.0
CREATE MATERIALIZED VIEW identity.all_permissions_with_related AS
 WITH RECURSIVE all_permissions AS (
         SELECT permissions.id AS permission_id,
            NULL::integer AS parent_id
           FROM identity.permissions
        UNION
         SELECT related_permissions.permission_id,
            related_permissions.related_permission_id
           FROM identity.related_permissions
        ), all_related_permissions AS (
         SELECT ap1.permission_id,
            ap1.parent_id AS related_permission_id
           FROM ( SELECT p1.permission_id AS parent_id,
                    p2.permission_id
                   FROM (all_permissions p1
                     JOIN all_permissions p2 ON ((p1.permission_id = p2.parent_id)))) ap1
        UNION ALL
         SELECT ap2.permission_id,
            arp.related_permission_id
           FROM (( SELECT p1.permission_id AS parent_id,
                    p2.permission_id
                   FROM (all_permissions p1
                     JOIN all_permissions p2 ON ((p1.permission_id = p2.parent_id)))) ap2
             JOIN all_related_permissions arp ON ((ap2.parent_id = arp.permission_id)))
        )
 SELECT all_related_permissions.permission_id,
    all_related_permissions.related_permission_id
   FROM all_related_permissions
UNION
 SELECT all_permissions.permission_id,
    all_permissions.permission_id AS related_permission_id
   FROM all_permissions
  WHERE (all_permissions.parent_id IS NULL)
  WITH NO DATA;

-- changeset reedws:2025-06-26-49 labels:v1.0.0
CREATE MATERIALIZED VIEW identity.all_role_permissions AS
 SELECT DISTINCT permissions.id,
    role_permissions.role_id,
    actions.code AS action,
    subjects.code AS subject,
    permissions.inverted
   FROM ((((identity.role_permissions
     JOIN identity.all_permissions_with_related ON ((role_permissions.permission_id = all_permissions_with_related.permission_id)))
     JOIN identity.permissions ON ((all_permissions_with_related.related_permission_id = permissions.id)))
     JOIN identity.actions ON ((permissions.action_id = actions.id)))
     JOIN identity.subjects ON ((permissions.subject_id = subjects.id)))
  ORDER BY permissions.inverted
  WITH NO DATA;

-- changeset reedws:2025-06-26-50 labels:v1.0.0
REFRESH MATERIALIZED VIEW identity.all_permissions_with_related;
REFRESH MATERIALIZED VIEW identity.all_role_permissions;

-- changeset reedws:2025-08-08-1 labels:v1.0.0
-- comment: Adding tables based on vision hearing database schema
CREATE SCHEMA IF NOT EXISTS reference;
CREATE SCHEMA IF NOT EXISTS organization;
CREATE SCHEMA IF NOT EXISTS people;
CREATE SCHEMA IF NOT EXISTS services;

CREATE TABLE reference.service_types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    code VARCHAR(10) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reference.grade_levels (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    code VARCHAR(10) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE organization.districts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    esc_name VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(name, esc_name)
);

CREATE TABLE organization.buildings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    district_id INTEGER NOT NULL REFERENCES organization.districts(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(name, district_id)
);

CREATE TABLE people.students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    date_of_birth DATE,
    grade_level_id INTEGER NOT NULL REFERENCES reference.grade_levels(id),
    county VARCHAR(50),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE services.therapist_districts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    therapist_id INTEGER NOT NULL REFERENCES identity.users(id) ON DELETE CASCADE,
    district_id INTEGER NOT NULL REFERENCES organization.districts(id) ON DELETE CASCADE,
    vision_or_hearing VARCHAR(20) NOT NULL CHECK (vision_or_hearing IN ('Vision', 'Hearing', 'Both')),
    is_active BOOLEAN DEFAULT TRUE,
    assigned_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(therapist_id, district_id, vision_or_hearing)
);

-- Student Enrollments (Historical tracking of student placements)
CREATE TABLE services.student_enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES people.students(id) ON DELETE CASCADE,
    billing_district_id INTEGER NOT NULL REFERENCES organization.districts(id),
    building_id INTEGER REFERENCES organization.buildings(id),
    district_of_attendance_id INTEGER REFERENCES organization.districts(id),
    district_of_residence_id INTEGER REFERENCES organization.districts(id),
    is_active BOOLEAN DEFAULT TRUE,
    enrollment_date DATE DEFAULT CURRENT_DATE,
    exit_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Ensure exit_date is after enrollment_date
    CONSTRAINT check_enrollment_dates CHECK (exit_date IS NULL OR exit_date >= enrollment_date)
);

-- Student Service Assignments (Which therapist provides which service to which student)
CREATE TABLE services.student_service_assignments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES people.students(id) ON DELETE CASCADE,
    therapist_id INTEGER NOT NULL REFERENCES identity.users(id) ON DELETE CASCADE,
    service_type_id INTEGER NOT NULL REFERENCES reference.service_types(id),
    is_active BOOLEAN DEFAULT TRUE,
    entry_date DATE DEFAULT CURRENT_DATE,
    exit_date DATE,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Ensure exit_date is after entry_date
    CONSTRAINT check_assignment_dates CHECK (exit_date IS NULL OR exit_date >= entry_date),

    -- Prevent duplicate active assignments for same student/service
    UNIQUE(student_id, service_type_id, is_active) DEFERRABLE INITIALLY DEFERRED
);

-- Service Documentation (All service records, notes, and time tracking)
CREATE TABLE services.documentation (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES people.students(id) ON DELETE CASCADE,
    therapist_id INTEGER NOT NULL REFERENCES identity.users(id) ON DELETE CASCADE,
    billing_district_id INTEGER NOT NULL REFERENCES organization.districts(id),
    service_date DATE NOT NULL,
    timestamp_recorded TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    case_notes TEXT,
    direct_minutes INTEGER DEFAULT 0 CHECK (direct_minutes >= 0),
    indirect_minutes INTEGER DEFAULT 0 CHECK (indirect_minutes >= 0),
    travel_minutes INTEGER DEFAULT 0 CHECK (travel_minutes >= 0),
    service_type_id INT NOT NULL REFERENCES reference.service_types(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- changeset reedws:2025-08-14-1 labels:v1.0.0
-- Drop the existing deferrable unique constraint
ALTER TABLE "services"."student_service_assignments" DROP CONSTRAINT "student_service_assignments_student_id_service_type_id_is_a_key";

-- Create new unique constraint that allows multiple therapists per student/service type
ALTER TABLE "services"."student_service_assignments" ADD CONSTRAINT "unique_service_assignments" UNIQUE ("student_id","service_type_id","therapist_id","entry_date");

-- changeset reedws:2025-08-20-1 labels:v1.0.0
UPDATE services.documentation SET created_at = timestamp_recorded;
ALTER TABLE services.documentation DROP COLUMN timestamp_recorded;

-- changeset reedws:2025-08-27-1 labels:v1.0.0
ALTER TABLE "services"."therapist_districts"
  ADD COLUMN "service_type_id" int,
  ADD FOREIGN KEY ("service_type_id") REFERENCES "reference"."service_types"("id");

UPDATE "services"."therapist_districts" SET "service_type_id" =
  CASE
    WHEN vision_or_hearing = 'Vision' THEN (SELECT id FROM reference.service_types WHERE code = 'VISION')
    WHEN vision_or_hearing = 'Hearing' THEN (SELECT id FROM reference.service_types WHERE code = 'HEARING')
    ELSE NULL
  END;

-- changeset reedws:2025-08-27-2 labels:v1.0.0
ALTER TABLE "services"."therapist_districts"
  DROP COLUMN "vision_or_hearing",
  ALTER COLUMN "service_type_id" SET NOT NULL;

-- changeset jarretkr:2025-09-04-10 labels:v1.0.0
-- comment: Create gender reference table
CREATE TABLE "reference"."gender" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "gender" text,
    PRIMARY KEY ("id")
);

-- changeset jarretkr:2025-09-04-11 labels:v1.0.0
-- comment: Populate gender reference table
INSERT INTO "reference"."gender"("gender") VALUES('Male') RETURNING "id", "gender";
INSERT INTO "reference"."gender"("gender") VALUES('Female') RETURNING "id", "gender";
INSERT INTO "reference"."gender"("gender") VALUES('Other') RETURNING "id", "gender";
INSERT INTO "reference"."gender"("gender") VALUES('Prefer Not to Say') RETURNING "id", "gender";

-- changeset jarretkr:2025-09-04-13 labels:v1.0.0
-- comment: Modify gender column to be unique and not null
ALTER TABLE "reference"."gender"
  ALTER COLUMN "gender" TYPE character varying(50),
  ADD UNIQUE ("gender"),
  ALTER COLUMN "gender" SET NOT NULL;

-- changeset jarretkr:2025-09-08-7 labels:v1.0.0
-- comment: Add unique constraint to organization.districts name column
ALTER TABLE "organization"."districts" ADD UNIQUE ("name");

-- changeset reedws:2025-10-10-1 labels:v1.0.0
-- comment: Adding educational_years table for issue 13
CREATE TABLE reference.educational_years (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(50) NOT NULL UNIQUE,
    start_date date,
    end_date date
);

-- changeset reedws:2025-10-10-2 labels:v1.0.0
-- comment: Adding initial data for educational_years table for issue 13
INSERT INTO reference.educational_years (name, start_date, end_date)
VALUES
  ('2024-2025', '2024-08-01', '2025-07-31'),
  ('2025-2026', '2025-08-01', '2026-07-31');

-- changeset reedws:2025-09-09-1 labels:v1.0.0
-- comment: Add audit columns to organization.districts table
ALTER TABLE "organization"."districts"
  ADD COLUMN "created_by" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "updated_by" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "deleted_by" INTEGER,
  ADD COLUMN "deleted_at" TIMESTAMP WITH TIME ZONE;

-- changeset reedws:2025-09-09-2 labels:v1.0.0
-- comment: Add audit columns to organization.buildings table
ALTER TABLE "organization"."buildings"
  ADD COLUMN "created_by" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "updated_by" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "deleted_by" INTEGER,
  ADD COLUMN "deleted_at" TIMESTAMP WITH TIME ZONE;

-- changeset reedws:2025-09-09-3 labels:v1.0.0
-- comment: Add audit columns to people.students table
ALTER TABLE "people"."students"
  ADD COLUMN "created_by" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "updated_by" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "deleted_by" INTEGER,
  ADD COLUMN "deleted_at" TIMESTAMP WITH TIME ZONE;

-- changeset reedws:2025-09-09-4 labels:v1.0.0
-- comment: Add audit columns to services.therapist_districts table
ALTER TABLE "services"."therapist_districts"
  ADD COLUMN "created_by" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "updated_by" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "deleted_by" INTEGER,
  ADD COLUMN "deleted_at" TIMESTAMP WITH TIME ZONE;

-- changeset reedws:2025-09-09-5 labels:v1.0.0
-- comment: Add audit columns to services.student_enrollments table
ALTER TABLE "services"."student_enrollments"
  ADD COLUMN "created_by" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "updated_by" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "deleted_by" INTEGER,
  ADD COLUMN "deleted_at" TIMESTAMP WITH TIME ZONE;

-- changeset reedws:2025-09-09-6 labels:v1.0.0
-- comment: Add audit columns to services.student_service_assignments table
ALTER TABLE "services"."student_service_assignments"
  ADD COLUMN "created_by" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "updated_by" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "deleted_by" INTEGER,
  ADD COLUMN "deleted_at" TIMESTAMP WITH TIME ZONE;

-- changeset reedws:2025-09-09-7 labels:v1.0.0
-- comment: Add audit columns to services.documentation table
ALTER TABLE "services"."documentation"
  ADD COLUMN "created_by" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "updated_by" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "deleted_by" INTEGER,
  ADD COLUMN "deleted_at" TIMESTAMP WITH TIME ZONE;

-- changeset reedws:2025-09-09-8 labels:v1.0.0
-- comment: Add foreign key constraints for audit columns to organization.districts
ALTER TABLE "organization"."districts"
  ADD CONSTRAINT "districts_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "districts_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "districts_deleted_by_fkey" FOREIGN KEY ("deleted_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-09-09-9 labels:v1.0.0
-- comment: Add foreign key constraints for audit columns to organization.buildings
ALTER TABLE "organization"."buildings"
  ADD CONSTRAINT "buildings_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "buildings_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "buildings_deleted_by_fkey" FOREIGN KEY ("deleted_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-09-09-10 labels:v1.0.0
-- comment: Add foreign key constraints for audit columns to people.students
ALTER TABLE "people"."students"
  ADD CONSTRAINT "students_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "students_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "students_deleted_by_fkey" FOREIGN KEY ("deleted_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-09-09-11 labels:v1.0.0
-- comment: Add foreign key constraints for audit columns to services.therapist_districts
ALTER TABLE "services"."therapist_districts"
  ADD CONSTRAINT "therapist_districts_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "therapist_districts_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "therapist_districts_deleted_by_fkey" FOREIGN KEY ("deleted_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-09-09-12 labels:v1.0.0
-- comment: Add foreign key constraints for audit columns to services.student_enrollments
ALTER TABLE "services"."student_enrollments"
  ADD CONSTRAINT "student_enrollments_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "student_enrollments_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "student_enrollments_deleted_by_fkey" FOREIGN KEY ("deleted_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-09-09-13 labels:v1.0.0
-- comment: Add foreign key constraints for audit columns to services.student_service_assignments
ALTER TABLE "services"."student_service_assignments"
  ADD CONSTRAINT "student_service_assignments_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "student_service_assignments_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "student_service_assignments_deleted_by_fkey" FOREIGN KEY ("deleted_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-09-09-14 labels:v1.0.0
-- comment: Add foreign key constraints for audit columns to services.documentation
ALTER TABLE "services"."documentation"
  ADD CONSTRAINT "documentation_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "documentation_updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  ADD CONSTRAINT "documentation_deleted_by_fkey" FOREIGN KEY ("deleted_by") REFERENCES "identity"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset reedws:2025-09-09-15 labels:v1.0.0
-- comment: Remove is_active columns in favor of deleted_at for soft deletes
ALTER TABLE "people"."students" DROP COLUMN "is_active";
ALTER TABLE "services"."therapist_districts" DROP COLUMN "is_active";
ALTER TABLE "services"."student_enrollments" DROP COLUMN "is_active";

-- changeset reedws:2025-09-09-16 labels:v1.0.0
-- comment: Drop and recreate the unique constraint for student_service_assignments without is_active
ALTER TABLE "services"."student_service_assignments" DROP CONSTRAINT "unique_service_assignments";
ALTER TABLE "services"."student_service_assignments" DROP COLUMN "is_active";
ALTER TABLE "services"."student_service_assignments" ADD CONSTRAINT "unique_active_service_assignments" UNIQUE ("student_id","service_type_id","therapist_id", "deleted_at") DEFERRABLE INITIALLY DEFERRED;

-- changeset reedws:2025-09-09-17 labels:v1.0.0
-- comment: Remove audit columns from roles table as it should not be audited
ALTER TABLE "identity"."roles" DROP COLUMN "created_by";
ALTER TABLE "identity"."roles" DROP COLUMN "created_at";
ALTER TABLE "identity"."roles" DROP COLUMN "updated_by";
ALTER TABLE "identity"."roles" DROP COLUMN "updated_at";
ALTER TABLE "identity"."roles" DROP COLUMN "deleted_by";
ALTER TABLE "identity"."roles" DROP COLUMN "deleted_at";

-- changeset jarretkr:2025-09-23-1 labels:v1.0.0
-- comment: Rename primary column in reference.genders table
ALTER TABLE "reference"."gender" RENAME TO "genders";
ALTER TABLE "reference"."genders" RENAME COLUMN "gender" TO "name";

-- changeset jarretkr:2025-09-30-1 labels:v1.0.0
-- comment: Remove code column from reference.genders table
ALTER TABLE "reference"."genders" DROP COLUMN "code";

-- changeset jarretkr:2025-10-08-3 labels:v1.0.0
-- comment: Create states table
CREATE TABLE "reference"."states" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying(50) NOT NULL,
    "code" character varying(2) NOT NULL,
    "created_at" timestamp NOT NULL,
    "updated_at" timestamp NOT NULL,
    "created_by" integer NOT NULL,
    "updated_by" integer NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("name"),
    UNIQUE ("code"),
    FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id"),
    FOREIGN KEY ("updated_by") REFERENCES "identity"."users"("id")
);

-- changeset jarretkr:2025-10-08-4 labels:v1.0.0
-- comment: Make audit columns nullable to allow inserts
ALTER TABLE "reference"."states"
  ALTER COLUMN "created_at" DROP NOT NULL,
  ALTER COLUMN "updated_at" DROP NOT NULL,
  ALTER COLUMN "created_by" DROP NOT NULL,
  ALTER COLUMN "updated_by" DROP NOT NULL;

-- changeset jarretkr:2025-10-08-5 labels:v1.0.0
-- comment: Insert US states into reference.states table
INSERT INTO "reference"."states"("name", "code") VALUES('Alabama', 'AL') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Alaska', 'AK') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Arizona', 'AZ') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Arkansas', 'AR') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('California', 'CA') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Colorado', 'CO') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Connecticut', 'CT') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Delaware', 'DE') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Florida', 'FL') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Georgia', 'GA') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Hawaii', 'HI') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Idaho', 'ID') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Illinois', 'IL') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Indiana', 'IN') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Iowa', 'IA') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Kansas', 'KS') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Kentucky', 'KY') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Louisiana', 'LA') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Maine', 'ME') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Maryland', 'MD') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Massachusetts', 'MA') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Michigan', 'MI') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Minnesota', 'MN') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Mississippi', 'MS') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Missouri', 'MO') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Montana', 'MT') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Nebraska', 'NE') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Nevada', 'NV') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('New Hampshire', 'NH') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('New Jersey', 'NJ') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('New Mexico', 'NM') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('New York', 'NY') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('North Carolina', 'NC') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('North Dakota', 'ND') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Ohio', 'OH') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Oklahoma', 'OK') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Oregon', 'OR') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Pennsylvania', 'PA') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Rhode Island', 'RI') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('South Carolina', 'SC') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('South Dakota', 'SD') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Tennessee', 'TN') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Texas', 'TX') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Utah', 'UT') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Vermont', 'VT') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Virginia', 'VA') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Washington', 'WA') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('West Virginia', 'WV') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Wisconsin', 'WI') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";
INSERT INTO "reference"."states"("name", "code") VALUES('Wyoming', 'WY') RETURNING "id", "name", "code", "created_at", "updated_at", "created_by", "updated_by";

-- changeset jarretkr:2025-10-14-1 labels:v1.0.0
-- comment: Create referrals table
CREATE TABLE "people"."referrals" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "educational_audiology" boolean DEFAULT false,
    "deaf_or_hard_of_hearing" boolean DEFAULT false,
    "email" character varying(50) NOT NULL,
    "person_requesting_service" text,
    "phone_number" text,
    "district_of_service_id" integer,
    "district_representative_name" text,
    "district_of_residence_id" integer,
    "billing_district_id" integer,
    "building_attending" text,
    "student_name" text NOT NULL,
    "grade_level_id" integer,
    "student_date_of_birth" date,
    "gender_id" integer,
    "city" text,
    "zip_code" text,
    "state_id" integer,
    "parent_guardian_name" text,
    "parent_guardian_phone_number" text,
    "created_at" timestamp NOT NULL,
    "created_by" integer NOT NULL,
    "updated_at" timestamp NOT NULL,
    "updated_by" integer NOT NULL,
    "deleted_at" timestamp,
    "deleted_by" integer,
    "completed_at" timestamp,
    PRIMARY KEY ("id"),
    CONSTRAINT "district_of_service_id_fkey" FOREIGN KEY ("district_of_service_id") REFERENCES "organization"."districts"("id"),
    CONSTRAINT "district_of_residence_id_fkey" FOREIGN KEY ("district_of_residence_id") REFERENCES "organization"."districts"("id"),
    CONSTRAINT "billing_district_id_fkey" FOREIGN KEY ("billing_district_id") REFERENCES "organization"."districts"("id"),
    CONSTRAINT "grade_level_id_fkey" FOREIGN KEY ("grade_level_id") REFERENCES "reference"."grade_levels"("id"),
    CONSTRAINT "gender_id_fkey" FOREIGN KEY ("gender_id") REFERENCES "reference"."genders"("id"),
    CONSTRAINT "state_id_fkey" FOREIGN KEY ("state_id") REFERENCES "reference"."states"("id"),
    CONSTRAINT "created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id"),
    CONSTRAINT "updated_by_fkey" FOREIGN KEY ("updated_by") REFERENCES "identity"."users"("id"),
    CONSTRAINT "deleted_by_fkey" FOREIGN KEY ("deleted_by") REFERENCES "identity"."users"("id")
);

-- changeset reedws:2025-09-23-1 labels:v1.0.0
-- comment: Adding schema to support filemaker data imports
ALTER TABLE "reference"."grade_levels" ADD COLUMN "order" int;

CREATE TABLE "organization"."buildings_grade_levels" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "grade_level_id" int NOT NULL,
    "building_id" int NOT NULL,
    "created_by" int NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_by" int NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "deleted_by" int,
    "deleted_at" timestamp with time zone,
    PRIMARY KEY ("id"),
    FOREIGN KEY ("grade_level_id") REFERENCES "reference"."grade_levels"("id"),
    FOREIGN KEY ("building_id") REFERENCES "organization"."buildings"("id"),
    FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id"),
    FOREIGN KEY ("updated_by") REFERENCES "identity"."users"("id"),
    FOREIGN KEY ("deleted_by") REFERENCES "identity"."users"("id")
);

ALTER TABLE "reference"."genders" ADD COLUMN "code" text;

ALTER TABLE "organization"."buildings"
  ALTER COLUMN "created_at" DROP DEFAULT,
  ALTER COLUMN "updated_at" DROP DEFAULT,
  ALTER COLUMN "created_by" DROP DEFAULT,
  ALTER COLUMN "updated_by" DROP DEFAULT,
  ALTER COLUMN "created_at" SET NOT NULL,
  ALTER COLUMN "updated_at" SET NOT NULL;

CREATE TABLE "reference"."counties" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" text NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("name")
);

CREATE TABLE "reference"."addresses" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "street1" text NOT NULL,
    "street2" text,
    "city" text NOT NULL,
    "state_id" int NOT NULL,
    "zip_code" text NOT NULL,
    "county_id" int,
    PRIMARY KEY ("id"),
    FOREIGN KEY ("state_id") REFERENCES "reference"."states"("id"),
    FOREIGN KEY ("county_id") REFERENCES "reference"."counties"("id")
);

ALTER TABLE "organization"."buildings"
  ADD COLUMN "address_id" int,
  ADD COLUMN "irn" text,
  ADD COLUMN "phone_number" text,
  ADD FOREIGN KEY ("address_id") REFERENCES "reference"."addresses"("id"),
  ADD UNIQUE ("irn");

ALTER TABLE "organization"."districts"
  ADD COLUMN "irn" text,
  ADD COLUMN "county_id" int,
  ADD UNIQUE ("irn"),
  ADD FOREIGN KEY ("county_id") REFERENCES "reference"."counties"("id");

CREATE TABLE "reference"."therapist_types" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" text NOT NULL,
    "code" text NOT NULL,
    PRIMARY KEY ("id")
);

ALTER TABLE "services"."student_service_assignments"
  ALTER COLUMN "entry_date" DROP DEFAULT,
  ALTER COLUMN "created_at" DROP DEFAULT,
  ALTER COLUMN "updated_at" DROP DEFAULT,
  ALTER COLUMN "created_by" DROP DEFAULT,
  ALTER COLUMN "updated_by" DROP DEFAULT,
  ADD COLUMN "therapist_type_id" int,
  ALTER COLUMN "entry_date" SET NOT NULL,
  ALTER COLUMN "created_at" SET NOT NULL,
  ALTER COLUMN "updated_at" SET NOT NULL,
  ADD COLUMN "omit_from_billing" boolean DEFAULT 'false',
  ADD FOREIGN KEY ("therapist_type_id") REFERENCES "identity"."actions"("id");

CREATE TABLE "reference"."medical_codes" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" text NOT NULL,
    "code" text NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "reference"."icd_codes" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" text NOT NULL,
    "code" text NOT NULL,
    PRIMARY KEY ("id")
);

ALTER TABLE "services"."documentation"
  ALTER COLUMN "created_at" DROP DEFAULT,
  ALTER COLUMN "created_at" TYPE timestamp with time zone,
  ALTER COLUMN "updated_at" DROP DEFAULT,
  ALTER COLUMN "updated_at" TYPE timestamp with time zone,
  ALTER COLUMN "submitted_on" TYPE timestamp with time zone,
  ALTER COLUMN "created_by" DROP DEFAULT,
  ALTER COLUMN "updated_by" DROP DEFAULT,
  ADD COLUMN "approved_at" timestamp with time zone,
  ADD COLUMN "begin_time" time,
  ADD COLUMN "end_time" time,
  ADD COLUMN "group_size" int,
  ADD COLUMN "location" text,
  ADD COLUMN "medical_code_id" int,
  ADD COLUMN "update_note" text,
  ADD COLUMN "objective" text,
  ADD COLUMN "is_tele_health" boolean DEFAULT 'false',
  ADD COLUMN "supervising_therapist_id" text,
  ADD COLUMN "icd_code_id" int,
  ALTER COLUMN "created_at" SET NOT NULL,
  ALTER COLUMN "updated_at" SET NOT NULL,
  ADD FOREIGN KEY ("medical_code_id") REFERENCES "reference"."medical_codes"("id"),
  ADD FOREIGN KEY ("icd_code_id") REFERENCES "reference"."icd_codes"("id");

CREATE TABLE "reference"."treatment_plan_statuses" (
    "id" integer GENERATED ALWAYS AS IDENTITY,
    "name" text NOT NULL,
    "code" text NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("code")
);

CREATE TABLE "services"."treatmeant_plans" (
    "id" integer GENERATED ALWAYS AS IDENTITY,
    "status_id" int,
    "activity" text,
    "amendment_description" text,
    "amended_at" timestamp with time zone,
    "amended_by" int,
    "diagnosis" text,
    "electronic_signature" text,
    "signed_on" timestamp with time zone,
    "parent_email" text,
    "goals" text,
    "student_grade_level_id" int,
    "mfe_date" timestamp with time zone,
    "parent_name" text,
    "parent_phone" text,
    "precaution" text,
    "student_id" int,
    "therapist_id" int,
    "plan_created_at" timestamp with time zone,
    "service_type_id" int,
    "created_by" int NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_by" int NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "deleted_by" int,
    "deleted_at" timestamp with time zone,
    PRIMARY KEY ("id"),
    FOREIGN KEY ("status_id") REFERENCES "reference"."treatment_plan_statuses"("id"),
    FOREIGN KEY ("amended_by") REFERENCES "identity"."users"("id"),
    FOREIGN KEY ("student_grade_level_id") REFERENCES "reference"."grade_levels"("id"),
    FOREIGN KEY ("student_id") REFERENCES "people"."students"("id"),
    FOREIGN KEY ("therapist_id") REFERENCES "identity"."users"("id"),
    FOREIGN KEY ("service_type_id") REFERENCES "reference"."service_types"("id"),
    FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id"),
    FOREIGN KEY ("updated_by") REFERENCES "identity"."users"("id"),
    FOREIGN KEY ("deleted_by") REFERENCES "identity"."users"("id")
);

ALTER TABLE "people"."students"
  ALTER COLUMN "created_at" DROP DEFAULT,
  ALTER COLUMN "created_at" TYPE timestamp with time zone,
  ALTER COLUMN "updated_at" DROP DEFAULT,
  ALTER COLUMN "updated_at" TYPE timestamp with time zone,
  ALTER COLUMN "created_by" DROP DEFAULT,
  ALTER COLUMN "updated_by" DROP DEFAULT,
  ADD COLUMN "middle_name" text,
  ALTER COLUMN "created_at" SET NOT NULL,
  ALTER COLUMN "updated_at" SET NOT NULL;

ALTER TABLE "services"."student_enrollments"
  ALTER COLUMN "enrollment_date" DROP DEFAULT,
  ALTER COLUMN "created_at" DROP DEFAULT,
  ALTER COLUMN "created_at" TYPE timestamp with time zone,
  ALTER COLUMN "updated_at" DROP DEFAULT,
  ALTER COLUMN "updated_at" TYPE timestamp with time zone,
  ALTER COLUMN "created_by" DROP DEFAULT,
  ALTER COLUMN "updated_by" DROP DEFAULT,
  ADD COLUMN "room_number" text,
  ADD COLUMN "teacher_name" text,
  ADD COLUMN "referral_date" date,
  ALTER COLUMN "created_at" SET NOT NULL,
  ALTER COLUMN "updated_at" SET NOT NULL;

-- changeset reedws:2025-09-23-2 labels:v1.0.0
-- comment: fixing audit cols
ALTER TABLE "organization"."buildings"
  ALTER COLUMN "created_at" TYPE timestamp with time zone,
  ALTER COLUMN "updated_at" TYPE timestamp with time zone;

ALTER TABLE "organization"."districts"
  ALTER COLUMN "created_at" DROP DEFAULT,
  ALTER COLUMN "created_at" TYPE timestamp with time zone,
  ALTER COLUMN "updated_at" DROP DEFAULT,
  ALTER COLUMN "updated_at" TYPE timestamp with time zone,
  ALTER COLUMN "created_by" DROP DEFAULT,
  ALTER COLUMN "updated_by" DROP DEFAULT,
  ALTER COLUMN "created_at" SET NOT NULL,
  ALTER COLUMN "updated_at" SET NOT NULL;

ALTER TABLE "people"."referrals"
  ALTER COLUMN "created_at" DROP DEFAULT,
  ALTER COLUMN "created_at" TYPE timestamp with time zone,
  ALTER COLUMN "updated_at" DROP DEFAULT,
  ALTER COLUMN "updated_at" TYPE timestamp with time zone,
  ALTER COLUMN "completed_at" TYPE timestamp with time zone,
  ALTER COLUMN "created_by" DROP DEFAULT,
  ALTER COLUMN "updated_by" DROP DEFAULT,
  ALTER COLUMN "deleted_at" TYPE timestamp with time zone,
  ALTER COLUMN "created_at" SET NOT NULL,
  ALTER COLUMN "updated_at" SET NOT NULL;

ALTER TABLE "reference"."service_types"
  DROP CONSTRAINT "service_types_name_key",
  ALTER COLUMN "created_at" DROP DEFAULT,
  ALTER COLUMN "created_at" TYPE timestamp with time zone,
  ALTER COLUMN "updated_at" DROP DEFAULT,
  ALTER COLUMN "updated_at" TYPE timestamp with time zone,
  ALTER COLUMN "created_at" SET NOT NULL,
  ALTER COLUMN "updated_at" SET NOT NULL;

ALTER TABLE "services"."student_service_assignments"
  ALTER COLUMN "created_at" TYPE timestamp with time zone,
  ALTER COLUMN "updated_at" TYPE timestamp with time zone;

ALTER TABLE "services"."therapist_districts"
  ALTER COLUMN "created_at" DROP DEFAULT,
  ALTER COLUMN "created_at" TYPE timestamp with time zone,
  ALTER COLUMN "updated_at" DROP DEFAULT,
  ALTER COLUMN "updated_at" TYPE timestamp with time zone,
  ALTER COLUMN "created_by" DROP DEFAULT,
  ALTER COLUMN "updated_by" DROP DEFAULT,
  ALTER COLUMN "created_at" SET NOT NULL,
  ALTER COLUMN "updated_at" SET NOT NULL;

-- changeset reedws:2025-09-23-3 labels:v1.0.0
-- comment: Added goals table
CREATE TABLE services.student_goals (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text,
    student_id integer NOT NULL REFERENCES people.students(id),
    treatment_plan_id integer NOT NULL REFERENCES services.treatmeant_plans(id),
    created_by integer NOT NULL REFERENCES identity.users(id),
    created_at timestamp with time zone NOT NULL,
    updated_by integer NOT NULL REFERENCES identity.users(id),
    updated_at timestamp with time zone NOT NULL,
    deleted_by integer REFERENCES identity.users(id),
    deleted_at timestamp with time zone
);
ALTER TABLE "services"."treatmeant_plans" DROP COLUMN "goals";

-- changeset nadipaca:2025-09-22-1 labels:v1.0.0
-- comment: Remove not null constraint from service date
ALTER TABLE "services"."documentation" ALTER COLUMN "service_date" DROP NOT NULL;

-- changeset reedws:2025-09-29-0 labels:v1.0.0
-- comment: insert service types
INSERT INTO "reference"."service_types" (name, code, created_at, updated_at) VALUES
  ('Vision', 'VISION', now(), now()),
  ('Hearing', 'HEARING', now(), now());

-- changeset reedws:2025-09-29-1 labels:v1.0.0
-- comment: Updating service types to have groups
CREATE TABLE "reference"."service_type_groups" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY,
    "name" text NOT NULL,
    "code" text NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("code")
);

ALTER TABLE "reference"."service_types"
  ADD COLUMN "service_type_group_id" int,
  ADD FOREIGN KEY ("service_type_group_id") REFERENCES "reference"."service_type_groups"("id");

INSERT INTO "reference"."service_type_groups" ("name", "code") VALUES
  ('Vision', 'VISION'),
  ('Hearing', 'HEARING');

ALTER TABLE "reference"."service_types"
  DROP COLUMN "created_at",
  DROP COLUMN "updated_at";

UPDATE "reference"."service_types" SET name = 'Teacher of the Visually Impaired', code = 'TVI', service_type_group_id = (SELECT id FROM "reference"."service_type_groups" WHERE code = 'VISION') WHERE code = 'VISION';
INSERT INTO "reference"."service_types" (name, code, service_type_group_id) VALUES ('Orientation and Mobility', 'O&M', (SELECT id FROM "reference"."service_type_groups" WHERE code = 'VISION'));
UPDATE "reference"."service_types" SET name = 'Audiologist', code = 'AUD', service_type_group_id = (SELECT id FROM "reference"."service_type_groups" WHERE code = 'HEARING') WHERE code = 'HEARING';
INSERT INTO "reference"."service_types" (name, code, service_type_group_id) VALUES ('Hearing Instrument Specialist', 'HIS', (SELECT id FROM "reference"."service_type_groups" WHERE code = 'HEARING'));

-- changeset reedws:2025-09-29-2 labels:v1.0.0
-- comment: Service type group is required
ALTER TABLE "reference"."service_types" ALTER COLUMN "service_type_group_id" SET NOT NULL;

-- changeset reedws:2025-10-08-1 labels:v1.0.0
-- comment: Adding migration user
INSERT INTO identity.users (id, first_name, last_name, email, password, created_by, created_at, updated_by, updated_at)
VALUES (0, 'Migration', 'User', 'NONE', 'NOLOGIN', 1, NOW(), 1, NOW());

-- changeset reedws:2025-10-08-2 labels:v1.0.0
-- comment: Insert grade levels
INSERT INTO reference.grade_levels (code, name, "order") VALUES
  ('PS', 'Preschool', 1),
  ('K', 'Kindergarten', 2),
  ('1', '1st Grade', 3),
  ('2', '2nd Grade', 4),
  ('3', '3rd Grade', 5),
  ('4', '4th Grade', 6),
  ('5', '5th Grade', 7),
  ('6', '6th Grade', 8),
  ('7', '7th Grade', 9),
  ('8', '8th Grade', 10),
  ('9', '9th Grade', 11),
  ('10', '10th Grade', 12),
  ('11', '11th Grade', 13),
  ('12', '12th Grade', 14),
  ('13', '13th Grade', 15);

-- changeset reedws:2025-10-08-3 labels:v1.0.0
-- comment: Fix unique constraint on therapist districts
CREATE UNIQUE INDEX "therapist_districts_unique" ON "services"."therapist_districts"("therapist_id","district_id","service_type_id","deleted_at");

-- changeset nadipaca:2025-10-17-2 labels:v1.0.0
-- comment: Create therapist service district view
CREATE VIEW services.therapist_service_district AS
WITH indirect_therapist_district AS (
  SELECT
    ssa.therapist_id,
    ssa.student_id,
    se.billing_district_id AS district_id,
    ssa.service_type_id,
    MIN(ssa.created_at) AS created_at,
    MAX(ssa.deleted_at) AS deleted_at
  FROM services.student_service_assignments ssa
  JOIN services.student_enrollments se
    ON ssa.student_id = se.student_id
  GROUP BY ssa.therapist_id, se.billing_district_id, ssa.service_type_id, ssa.student_id
),
direct_therapist_district AS (
  SELECT
    therapist_id,
    district_id,
    service_type_id,
    MIN(created_at) AS created_at,
    MAX(deleted_at) AS deleted_at
  FROM services.therapist_districts
  GROUP BY therapist_id, district_id, service_type_id
)
SELECT
  itd.therapist_id,
  itd.district_id,
  itd.service_type_id,
  itd.created_at,
  itd.deleted_at,
  itd.student_id,
  CASE
    WHEN EXISTS (
      SELECT 1 FROM services.therapist_districts dtd
      WHERE dtd.therapist_id = itd.therapist_id
        AND dtd.district_id = itd.district_id
    ) THEN FALSE
    ELSE TRUE
  END AS is_external
FROM indirect_therapist_district itd

UNION

SELECT
  dtd.therapist_id,
  dtd.district_id,
  dtd.service_type_id,
  dtd.created_at,
  dtd.deleted_at,
  NULL AS student_id,
  FALSE AS is_external
FROM direct_therapist_district dtd;

-- changeset jarretkr:2025-10-16-1 labels:v1.0.0
-- comment: Drop NOT NULL constraint on student_id
ALTER TABLE "services"."documentation" ALTER COLUMN "student_id" DROP NOT NULL;

-- changeset reedws:2025-10-27-1 labels:v1.0.0
-- comment: Rename educational_years to academic_years
ALTER TABLE "reference"."educational_years" RENAME TO "academic_years";

-- changeset reedws:2025-10-27-2 labels:v1.0.0
-- comment: Add academic year foreign key to enrollments and service assignments
ALTER TABLE "services"."student_enrollments"
  ADD COLUMN "academic_year_id" int,
  ADD FOREIGN KEY ("academic_year_id") REFERENCES "reference"."academic_years"("id");
ALTER TABLE "services"."student_service_assignments"
  ADD COLUMN "academic_year_id" int,
  ADD FOREIGN KEY ("academic_year_id") REFERENCES "reference"."academic_years"("id");

-- changeset reedws:2025-10-27-3 labels:v1.0.0
-- comment: Move grade level to enrollments
ALTER TABLE "services"."student_enrollments"
  ADD COLUMN "grade_level_id" int,
  ADD FOREIGN KEY ("grade_level_id") REFERENCES "reference"."grade_levels"("id");

-- changeset reedws:2025-10-27-4 labels:v1.0.0
-- comment: Migrate existing grade levels to enrollments
UPDATE "services"."student_enrollments" set grade_level_id = s.grade_level_id
FROM "people"."students" s
WHERE "services"."student_enrollments".student_id = s.id;

-- changeset reedws:2025-10-27-5 labels:v1.0.0
-- comment: Make grade level required on enrollments
ALTER TABLE "services"."student_enrollments"
  ALTER COLUMN "grade_level_id" SET NOT NULL;

-- changeset reedws:2025-10-27-6 labels:v1.0.0
-- comment: Remove grade level from students
ALTER TABLE "people"."students" DROP COLUMN "grade_level_id";

-- changeset nadipaca:2025-10-28 labels:v1.0.0
-- comment: Drop NOT NULL constraint on service_type_id
ALTER TABLE "services"."documentation" ALTER COLUMN "service_type_id" DROP NOT NULL;

-- changeset jarretkr:2025-10-28-1 labels:v1.0.0
-- comment: Create user_service_types table
CREATE TABLE "identity"."user_service_types" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" integer NOT NULL,
    "service_type_id" integer NOT NULL,
    "created_at" timestamp,
    "created_by" integer,
    "updated_at" timestamp,
    "updated_by" integer,
    "deleted_at" timestamp,
    "deleted_by" integer,
    PRIMARY KEY ("id"),
    FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id"),
    FOREIGN KEY ("service_type_id") REFERENCES "reference"."service_types"("id")
);

-- changeset jarretkr:2025-10-28-2 labels:v1.0.0
-- comment: Create user_service_type_groups table
CREATE TABLE "identity"."user_service_type_groups" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" integer NOT NULL,
    "service_type_group_id" integer NOT NULL,
    "created_at" timestamp,
    "created_by" integer,
    "updated_at" timestamp,
    "updated_by" integer,
    "deleted_at" timestamp,
    "deleted_by" integer,
    PRIMARY KEY ("id"),
    FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id"),
    FOREIGN KEY ("service_type_group_id") REFERENCES "reference"."service_type_groups"("id")
);

-- changeset reedws:2025-11-10-0 labels:v1.0.0
-- comment: Add name to permissions and related permissions
ALTER TABLE "identity"."permissions" ADD COLUMN "name" text NOT NULL;
ALTER TABLE "identity"."related_permissions" ADD COLUMN "name" text NOT NULL;

-- changeset reedws:2025-11-10-1 labels:v1.0.0
-- comment: Add roles
INSERT INTO identity.roles (name, code) VALUES
  ('Therapist', 'THERAPIST'),
  ('Supervisor', 'SUPERVISOR'),
  ('Admin Assistant', 'ADMIN_ASSISTANT'),
  ('Director', 'DIRECTOR');

UPDATE identity.roles SET name = 'Super Admin' WHERE code = 'ADMIN';

-- changeset reedws:2025-11-10-2 labels:v1.0.0
-- comment: Add permissions
INSERT INTO identity.permissions (action_id, subject_id, name) VALUES
  ((SELECT id FROM identity.actions WHERE code = 'CREATE'), (SELECT id FROM identity.subjects WHERE code = 'USER'), 'Create User'),
  ((SELECT id FROM identity.actions WHERE code = 'READ'), (SELECT id FROM identity.subjects WHERE code = 'USER'), 'Read User'),
  ((SELECT id FROM identity.actions WHERE code = 'UPDATE'), (SELECT id FROM identity.subjects WHERE code = 'USER'), 'Update User'),
  ((SELECT id FROM identity.actions WHERE code = 'DELETE'), (SELECT id FROM identity.subjects WHERE code = 'USER'), 'Delete User'),
  ((SELECT id FROM identity.actions WHERE code = 'RESTORE'), (SELECT id FROM identity.subjects WHERE code = 'USER'), 'Restore User'),
  ((SELECT id FROM identity.actions WHERE code = 'READ'), (SELECT id FROM identity.subjects WHERE code = 'ROLE'), 'Read Role');

-- changeset reedws:2025-11-10-3 labels:v1.0.0
-- comment: Add Related permissions
INSERT INTO identity.related_permissions (name, permission_id, related_permission_id) VALUES
  (
    'If you can update a user, you can read roles',
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'UPDATE' AND s.code = 'USER'),
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'READ' AND s.code = 'ROLE')
  ),
  (
    'If you can create a user, you can read roles',
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'CREATE' AND s.code = 'USER'),
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'READ' AND s.code = 'ROLE')
  ),
  (
    'If you can delete a user, you can update a user',
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'DELETE' AND s.code = 'USER'),
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'UPDATE' AND s.code = 'USER')
  ),
  (
    'If you can restore a user, you can update a user',
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'RESTORE' AND s.code = 'USER'),
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'UPDATE' AND s.code = 'USER')
  ),
  (
    'If you can create a user, you can read users',
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'CREATE' AND s.code = 'USER'),
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'READ' AND s.code = 'USER')
  ),
  (
    'If you can update a user, you can read users',
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'UPDATE' AND s.code = 'USER'),
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'READ' AND s.code = 'USER')
  )

-- changeset reedws:2025-11-10-4 labels:v1.0.0
-- comment: Assign permissions to roles
INSERT INTO identity.role_permissions (role_id, permission_id) VALUES
  -- Admin Permissions
  (
    -- Create user
    (SELECT id FROM identity.roles WHERE code = 'ADMIN'),
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'CREATE' AND s.code = 'USER')
  ),
  (
    -- Update user
    (SELECT id FROM identity.roles WHERE code = 'ADMIN'),
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'UPDATE' AND s.code = 'USER')
  ),
  (
    -- Delete user
    (SELECT id FROM identity.roles WHERE code = 'ADMIN'),
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'DELETE' AND s.code = 'USER')
  ),
  (
    -- Restore user
    (SELECT id FROM identity.roles WHERE code = 'ADMIN'),
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'RESTORE' AND s.code = 'USER')
  );

-- changeset reedws:2025-11-10-5 labels:v1.0.0
-- comment: Refresh permission materialized views
REFRESH MATERIALIZED VIEW identity.all_permissions_with_related;
REFRESH MATERIALIZED VIEW identity.all_role_permissions;

-- changeset reedws:2025-11-12-1 labels:v1.0.0
-- comment: Add role for district representative
INSERT INTO identity.roles (name, code) VALUES
  ('District Representative', 'DISTRICT_REP');

-- changeset cashieas:2025-11-25-1 labels:v1.0.0
-- comment: Add STUDENT subject
INSERT INTO "identity".subjects (code, name, active)
VALUES ('STUDENT', 'Students', TRUE)

-- Add READ STUDENT permission
INSERT INTO identity.permissions (action_id, subject_id, name) VALUES
  ((SELECT id FROM identity.actions WHERE code = 'READ'), (SELECT id FROM identity.subjects WHERE code = 'STUDENT'), 'Read Student');

-- changeset cashieas:2025-12-01-1 labels:v1.0.0
-- comment: Assign READ STUDENT permission to ADMIN role
INSERT INTO identity.role_permissions (role_id, permission_id) VALUES
  (
    (SELECT id FROM identity.roles WHERE code = 'ADMIN'),
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'READ' AND s.code = 'STUDENT')
  );

-- changeset cashieas:2025-12-01-2 labels:v1.0.0
-- comment: Assign READ STUDENT permission to THERAPIST role
INSERT INTO identity.role_permissions (role_id, permission_id) VALUES
  (
    (SELECT id FROM identity.roles WHERE code = 'THERAPIST'),
    (SELECT p.id FROM identity.permissions p
      JOIN identity.actions a ON p.action_id = a.id
      JOIN identity.subjects s ON p.subject_id = s.id
      WHERE a.code = 'READ' AND s.code = 'STUDENT')
  );

-- changeset cashieas:2025-11-25-4 labels:v1.0.0
-- comment: Refresh materialized views after permission changes
REFRESH MATERIALIZED VIEW identity.all_permissions_with_related;
REFRESH MATERIALIZED VIEW identity.all_role_permissions;

-- changeset nadipaca:2025-11-14-1 labels:v1.0.0
-- comment: Add status tracking columns to referrals table
ALTER TABLE "people"."referrals"
    ADD COLUMN "status_id" integer,
    ADD COLUMN "comment" text,
    ADD COLUMN "status_by" integer,
    ADD COLUMN "status_at" timestamp with time zone,
    ADD CONSTRAINT "referrals_status_by_fkey" FOREIGN KEY ("status_by") REFERENCES "identity"."users"("id"),
    ADD CONSTRAINT "referrals_status_id_fkey" FOREIGN KEY ("status_id") REFERENCES "people"."referral_statuses"("id");


-- changeset nadipaca:2025-11-21-1 labels:v1.0.0
-- comment: Create referral_statuses table and seed initial data
CREATE TABLE "reference"."referral_statuses" (
    "id" integer GENERATED ALWAYS AS IDENTITY,
    "name" text NOT NULL,
    "code" text NOT NULL,
    "sort_order" integer NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("code")
);

-- changeset nadipaca:2025-11-21-2 labels:v1.0.0
-- comment: Insert referral status records
INSERT INTO "reference"."referral_statuses" ("code", "name", "sort_order") VALUES
    ('DRAFT', 'Draft', 0),
    ('NEW', 'New', 1),
    ('PENDING_THERAPIST_ASSIGNMENT', 'Pending Therapist Assignment', 2),
    ('NEED_INFO', 'Need Information', 3),
    ('PROCESSED', 'Processed', 4);

-- changeset nadipaca:2025-11-22-1 labels:v1.0.0
-- comment: Create referral_status_history table to track status changes
CREATE TABLE "people"."referral_status_history" (
    "id" integer GENERATED ALWAYS AS IDENTITY,
    "referral_id" integer NOT NULL,
    "status_id" integer NOT NULL,
    "created_by" integer NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT NOW(),
    PRIMARY KEY ("id"),
    FOREIGN KEY ("referral_id") REFERENCES "people"."referrals"("id"),
    FOREIGN KEY ("status_id") REFERENCES "reference"."referral_statuses"("id"),
    FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id")
);

-- changeset nadipaca:2025-11-22-2 labels:v1.0.0
-- comment: Update status_id foreign key constraints to reference reference.referral_statuses
ALTER TABLE "people"."referrals"
  ADD CONSTRAINT "referrals_status_id_fkey" FOREIGN KEY ("status_id") REFERENCES "reference"."referral_statuses"("id");
  DROP COLUMN "comment";
  ALTER COLUMN "status_id" SET NOT NULL,
  ALTER COLUMN "status_by" SET NOT NULL

-- changeset nadipaca:2025-11-25-1 labels:v1.0.0
-- comment: Create documentation_monthly_summary view
CREATE OR REPLACE VIEW services.documentation_monthly_summary AS
SELECT
  "student_id",
  "therapist_id",
  EXTRACT(YEAR FROM "service_date")::INTEGER AS year,
  EXTRACT(MONTH FROM "service_date")::INTEGER AS month,
  SUM("direct_minutes") AS total_direct_minutes
FROM services.documentation
WHERE "service_date" IS NOT NULL
  AND "student_id" IS NOT NULL
GROUP BY "student_id", "therapist_id", EXTRACT(YEAR FROM "service_date"), EXTRACT(MONTH FROM "service_date")
ORDER BY "student_id", "therapist_id", year, month;
